- name: Protect against brute-force login attacks.
  ufw:
    rule: limit
    port: ssh
    proto: tcp
- name: UFW - Allow SSH connections.
  ufw:
    rule: allow
    name: OpenSSH
- name: Allow ssh to use  port 2244
  ufw:
    rule: allow
    port: '2244'
    proto: tcp

- name: Setup alternate port for SSH
  lineinfile:
     dest: "/etc/ssh/sshd_config"
     regexp: "^Port"
     line: "Port 2244"

- name: Allow port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow port 3306 for mysql
  ufw:
    rule: allow
    port: '3306'
    proto: tcp
- name: UFW - Deny all other incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming
